### ISSUE TITLE
StandardEcu.setCurrentRequest(null)

### ISSUE THREAD

**Issue by marco-wehnert** [doip/doip#24]
In the current implementation the function "setCurrentRequest(null)" will be called after the three functions "processMessageBy..." the request will be set to null, so the ECU can receive new requests. But in case the ECU wants to delay a response, for example first send a response pending (0x78) and later sends the real answer then a new request can be handled but the ECU is not ready.

The following convention shall apply: When functions handle a request and send the response then the function itself is responsible to set the current request to null.

**Comment by marco-wehnert** [comment]
When in the lookup table a entry will match then the current request shall be set to null.

**Comment by doip** [comment]
solved
