### ISSUE TITLE
Standard ECU "isBusy" flag not handled correctly

### ISSUE THREAD

**Issue by doip** [doip/doip#25]
The is busy flag is not handled correctly. The response with NRC 0x21 will send wrong SID.

Would be good if that bug can be verified at first in a unit test.

**Comment by marco-wehnert** [comment]
The test helper classes are not designed for tests with multiple responses from the gateway, so a unit test which fails had not been implemented. Instead the result is visible in the log file. Manual check required

**Comment by marco-wehnert** [comment]
Implemented in commit d5973a48dcb3ab4237705c9d645b653889ec78d9
