### ISSUE TITLE
Support suppressPosRspMsgIndicationBit 

### ISSUE THREAD

**Issue by stevenfoot** [doip/doip#35]
If the highest bit of the second byte in a request is set no positve response shall be send from the ecu. 
(ISO  14229-1 UDS). The simulation shall handle this. This means a ackn shall be send but no diagnostic response message.

**Comment by marco-wehnert** [comment]
The lookup tables now support empty response, so you can define now requests where no response will be send:
```
3E 00 : 7E 00 
3E 80 : 
```

In the function "processRequestAfterLookupTable" it's up to the user to realize the handling of suppress positive response bit. Default handling is sending negative response with NRC 0x10. If no response shall be sent then just check suppress positive response bit and call "clearCurrentRequest" without calling "onSendUdsMessage".

Implemented in Release 1.1.2, depending releases are defined in build.gradle file.

**Comment by marco-wehnert** [comment]
Can we close this issue? We released now doip-custom-simulation 1.1.4 this feature is implemented.

**Comment by stevenfoot** [comment]
You can close it. I adapt my simulation files to this solution.
