### ISSUE TITLE
Sync pattern in vehicle identification request message

### ISSUE THREAD

**Issue by marco-wehnert** [doip/doip#37]
Wireshark declares a vehicle identification request message with VIN as invalid DoIP message because the sync pattern is 0xFF 00. 
A vehicle identification request message with EID and sync pattern FF 00 is declared as valid format.
A vehicle identification request message (no VIN, no EID) must have 0xFF 00 as sync pattern. But How about the other two messages? must they have synch pattern 0x02 FD?

Shall this be configurable to choose between both sync patterns? We could make all messages sync pattern configurable, but it would be a little bit more effort.

**Comment by stevenfoot** [comment]
FF 00 is reserved from ISO 13400-2. It is used from older ecus of one german car maker. This doip implementation has serveral small differences to ISO 13400-2. I think wireshark accept FF 00 for this older ecus. 
But this ecus have no implementation for vehicle indentification request with VIN. 
For the simulation sync pattern FF 02 (actual iso spec) is ok.

**Comment by stevenfoot** [comment]
No need for a new configuration
